### ISSUE TITLE
Emby 

### ISSUE THREAD

**Issue by Moimemeici** [xataz/docker-emby#10]
Salut, 
pourrais tu modifié ton dockerfile pour avoir la dernière version stp ?
D'ailleurs j'ai tenté de créer le conteneur en utilisant ton dockerfile mais j'ai une erreur qui vient clairement de moi.

**Comment by cactushydrocodone** [comment]
@Moimemeici Please write in english so everyone understands you.
@xataz The dockerfile is outdated, and he gets an error with the newest version of your dockerfile

**Comment by Moimemeici** [comment]
Yes, sorry.

I have this error 

> Removing intermediate container 72bd108b87ae
> Step 9/12 : ADD rootfs /
> ADD failed: stat /var/lib/docker/tmp/docker-builder410318007/rootfs: no such file or directory
>
